services:
  mongodb:
    image: mongo:latest
    container_name: fase4cliente
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: fase4cliente
    ports:
      - "27021:27017"

  fase4-cliente:
    image: fase4-cliente:latest
    container_name: fase4-cliente-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/fase4cliente
    depends_on:
      - mongodb
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
